# contacts blueprint
# don't need a title field as it is generated by default on all post types...
title: Contact
type:  contact
titlelabel: What is your name?
fields:
	email:
		label: What is your email address?
		type:  email
		size:  large
		adminonly: false
	subject:
		label: What did you want to talk about?
		type:  text
		size:  large
		adminonly: false
	message: 
		label: What did you want to say?
		type:  textarea
		size:  large
		adminonly:	false
	contacted:
		label: Did you contact this contact?
		type:  radio
		options: yes;no
		size:  large
		adminonly: true
	contacttype:
		label: What type of contact was this contact?
		type:  dropdown
		options: client;lead;talk
		size:  large
		adminonly: true
