# default blueprint
# don't need a title field as it is generated by default on all post types...
title: Page
type:  page
titlelabel: Name
fields:
	body: 
		label: Body of Page
		type:  textarea
		size:  large
		adminonly:	false
	sort:
		label: Sort Order
		type:	number
		size:	large
		adminonly:	true