# default blueprint
# don't need a title field as it is generated by default on all post types...
title: Tag
type:  tag
titlelabel: Name
prefix: /tag/
fields:
	nofield:
		label: ""
		type:	hidden
		size:	large
		adminonly:	true